---
title: "TEDS_A_2012_Sankey"
author: "J. Hagedorn"
date: "Tuesday, July 01, 2014"
output: html_document
---


### Get and process data

Load the dataset.
```{r}
load("~/GitHub/TEDS/data/TEDS_A/2012/35037-0001-Data.rda")
TEDS_A_2012 <- da35037.0001
```

Change class of variables.
```{r}
TEDS_A_2012$YEAR <- as.factor(TEDS_A_2012$YEAR)
TEDS_A_2012$DAYWAIT <- as.numeric(TEDS_A_2012$DAYWAIT)
```

Subset for Michigan & remove NA values:
```{r}
MI_A_2012 <- subset(TEDS_A_2012, STFIPS == '(26) MICHIGAN')
naOmit_A_2012 <- subset(MI_A_2012, !is.na(LIVARAG)&!is.na(SERVSETA))
```

Format data for use in sankey diagram:
```{r}
library(dplyr)
dat_A_12 <- summarise(group_by(naOmit_A_2012,LIVARAG,SERVSETA), Weight=n())
```


### Create Sankey diagram

```{r results = 'asis'}
library(googleVis)
skA12 <- gvisSankey(dat_A_12, from="LIVARAG", to="SERVSETA", weight="Weight",
                  options=list(width=800, height=600,
                               sankey="{link: {color: { fill: '#d799ae' } },
                               node: { color: { fill: '#a61d4c' },
                               label: { color: '#871b47' } }}"))
print(skA12, "chart") 
```
